[tools]
node = "22"
pnpm = "latest"

[tasks]
dev = "pnpm dev"
build = "pnpm build"
preview = "pnpm preview"
fetch-data = "pnpm fetch-data"
deploy = "pnpm build:static && pnpm deploy"
"deploy:preview" = "pnpm build:static && pnpm deploy:preview"
